name: Formatting check

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
      - '3rdparty/*'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
      - '3rdparty/*'
  workflow_dispatch:

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: RPCSX/rpcsx
        ref: master
    - name: Pre-Format
      run: |
        clang-format -style=llvm -dump-config > .clang-format
        find . -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.11.0
      with:
        exclude-regex: (libspirv|3rdparty)
        clang-format-version: 16
