name: Build RPCSX

on:
  push:
  workflow_dispatch:

jobs:
  build-rpcsx:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Setup dependencies
      run: |
        sudo dnf install -y git cmake lld gcc-c++ gcc libunwind-devel glfw-devel vulkan-devel vulkan-validation-layers-devel spirv-tools glslang-devel spirv-tools-devel xbyak-devel
        git config --global --add safe.directory '*'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: RPCSX/rpcsx
        ref: master
        submodules: recursive

    - name: Setup SPIRV-Cross
      run: |
        git clone https://github.com/KhronosGroup/SPIRV-Cross 
        cd SPIRV-Cross 
        mkdir build && cd build 
        cmake .. && cmake --build . 
        sudo make install

    - name: Build RPCSX
      run: |
        cmake -B build
        cmake --build build -j4
      env:
        LDFLAGS: -Wl,--no-relax

    - name: Upload RPCSX
      uses: actions/upload-artifact@v3
      with:
        name: rpcsx-bin
        path: build/bin/*
        if-no-files-found: error
