name: Build RPCSX

on:
  push:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  pull_request:
    paths-ignore:
      - "**/*.md"
      - '**/*.txt'
  workflow_dispatch:

jobs:
  build-rpcsx:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Setup dependencies
      run: |
        sudo dnf install -y git cmake libunwind-devel glfw-devel vulkan-devel vulkan-validation-layers-devel spirv-tools glslang-devel gcc-c++ gcc spirv-tools-devel xbyak-devel
        git config --global --add safe.directory '*'
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive


        
    - name: Build RPCSX
      run: |
        cmake -B build
        cmake --build build -j4

    - name: Upload RPCSX
      uses: actions/upload-artifact@v3
      with:
        name: rpcsx-bin
        path: build/bin/*
        if-no-files-found: error
