name: Build RPCSX

on:
  workflow_dispatch:

jobs:
  build-rpcsx:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: RPCSX/rpcsx
        ref: master
        submodules: recursive
    - name: Checkout AppImage Repo
      uses: actions/checkout@v3
      with:
          clean: false
          path: ci
          
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential libunwind-dev \
        libglfw3-dev libvulkan-dev vulkan-validationlayers-dev \
        spirv-tools glslang-tools libspirv-cross-c-shared-dev libfuse2

    - name: Setup Vulkan Headers
      run: |
        VULKANVER=1.3.259
        curl -sSfLo Vulkan-Headers.tar.gz https://github.com/KhronosGroup/Vulkan-Headers/archive/v${VULKANVER}.tar.gz
        tar -xf Vulkan-Headers*.tar.gz
        cd Vulkan-Headers*/ 
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
        make -j$(nproc)
        sudo make install

    - name: Build RPCSX
      run: |
        cmake -B build && \
        cmake --build build -j4

    - name: Package RPCSX AppImage
      run: |
        chmod +x ci/.github/assets/appimage.sh
        ci/.github/assets/appimage.sh
        mkdir -p artifacts
        cp rpcsx.AppImage artifacts/

    - name: Upload RPCSX
      uses: actions/upload-artifact@v3
      with:
        name: rpcsx-bin
        path: artifacts
        if-no-files-found: error
